[global]

[hasura]
version = "v2.46.0-ce"
adminSecret = "{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}"
webhookSecret = "{{ secrets.NHOST_WEBHOOK_SECRET }}"

[[hasura.jwtSecrets]]
type = "HS256"
key = "{{ secrets.HASURA_GRAPHQL_JWT_SECRET }}"

[hasura.settings]
corsDomain = ["*"]
devMode = false
enableConsole = true

[auth]
version = "0.41.0"

[auth.redirections]
clientUrl = "https://rrbtsubvwmsqbnqyubmc.nhost.app"
allowedUrls = ["https://rrbtsubvwmsqbnqyubmc.nhost.app", "http://localhost:3000"]

[auth.signUp]
enabled = true

[auth.user]
[auth.user.roles]
default = "user"
allowed = ["user"]

[auth.session]
accessToken.expiresIn = 900
refreshToken.expiresIn = 43200

[auth.method.emailPassword]
emailVerificationRequired = true
passwordMinLength = 8

[postgres]
version = "14.18-20250728-1"

[postgres.resources]
[postgres.resources.storage]
capacity = 1

[storage]
version = "0.7.2"

[observability]
[observability.grafana]
adminPassword = "{{ secrets.GRAFANA_ADMIN_PASSWORD }}"




