[global]

[hasura]
version = 'v2.46.0-ce'
adminSecret = 'nhost-admin-secret'
webhookSecret = 'nhost-webhook-secret'

[hasura.settings]
corsDomain = ['*']
devMode = false
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false

[auth]
version = '0.39.0-beta6'

[auth.signUp]
enabled = true

[auth.user]
[auth.user.roles]
default = 'user'
allowed = ['user']

[auth.session]
[auth.session.accessToken]
expiresIn = 900

[auth.session.refreshToken]
expiresIn = 43200

[auth.method.emailPassword]
hibpEnabled = false
emailVerificationRequired = true
passwordMinLength = 8

[postgres]
version = '14.6-20221215-1'

[postgres.resources.storage]
capacity = 1

[storage]
version = '0.7.1'


